osx_image: xcode10
language: objective-c
sudo: required

cache:
  directories:
  - Carthage

env:
  global:
    - PROJECT="RxVipKit.xcodeproj"
    - SCHEME="RxVipKit"
    - IOS_SDK="iphonesimulator12.0"
    - DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=12.0"

before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
  - brew install swiftlint
  - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
before_script:
  - carthage bootstrap --platform iOS --no-use-binaries --cache-builds

script:
  - xcodebuild clean build test
    -project "$PROJECT"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    -enableCodeCoverage YES
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`

after_success:
  - bash <(curl -s https://codecov.io/bash) -X xcodeplist -J 'RxVipKit'